spring:
  application:
    name: ms-matricula

  datasource:
    url: jdbc:postgresql://localhost:5432/ms_matricula
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect



server:
  port: 7569


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8094/eureka
  instance:
    hostname: localhost
